### ISSUE TITLE
Restore number of CPUs

### ISSUE THREAD

**Issue by giovannipizzi** [marvel-nccr/ansible-role-slurm#1]
In 5d278262912cc419165c61c9f00ef523ddadd1ea the directive `CPUs={{ slurm_cpus }}` was removed from `slurm.conf` because it led to `error: Node configuration differs from hardware: Procs=2:2(hw) Boards=1:1(hw) SocketsPerBoard=2:1(hw) CoresPerSocket=1:2(hw) ThreadsPerCore=1:1(hw)`.

However, now submitting jobs with more than 1 CPU, e.g. with the script below, doesn't work and the job remains in the queue forever as resources are missing.
```
#!/bin/bash
#SBATCH --no-requeue
#SBATCH --job-name="aiida-24"
#SBATCH --get-user-env
#SBATCH --output=_scheduler-stdout.txt
#SBATCH --error=_scheduler-stderr.txt
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=2
#SBATCH --time=00:30:00


ulimit -s unlimited

sleep 10

date
```

I tried and, from the results, I gather than:
- Using only `NodeName={{ slurm_hostname }} State=UNKNOWN `:
  -  implicitly means CPUs=1
  - Also in this case, I get an error in the log: `error: Node configuration differs from hardware: Procs=1:2(hw) Boards=1:1(hw) SocketsPerBoard=1:1(hw) CoresPerSocket=1:2(hw) ThreadsPerCore=1:1(hw)` 
  - The queue works when submitting jobs with 1 CPU only
  - I imagine therefore that this "error" is actually a "warning" and is not critical
- Using only `NodeName={{ slurm_hostname }} CPUs=2 State=UNKNOWN `:
  -  assigns 2 CPUs
  - the "error" I get is `error: Node configuration differs from hardware: Procs=2:2(hw) Boards=1:1(hw) SocketsPerBoard=2:1(hw) CoresPerSocket=1:2(hw) ThreadsPerCore=1:1(hw)`
  - the queue works both with 1CPU and 2CPU jobs

So I think that we need to revert the commit above, also because AiiDA is then configured to have a default of 2CPUs per machine on localhost.

Note that, however, the user could start the virtual machine with a different number of virtual CPUs... I don't know what happens in this case. From the results above, if the number of vCPUs is > the ones in the slurm configuration, there is no problem. One should probably try to reboot the VM with 1 CPU only and see if the queue is completely blocked, or if slurm still works, but overbooks the single vCPU.

Finally, I think that the syntax of the "error" is `current:expected`. Therefore, in the error for `CPUs=2`: `Procs=2:2(hw) Boards=1:1(hw) SocketsPerBoard=2:1(hw) CoresPerSocket=1:2(hw) ThreadsPerCore=1:1(hw)` the problem is simply in the splitting of SocketsPerBoard and CoresPerSocket. My guess is that, for a VM not tuned for HPC, we can safely ignore this (even if I'm pretty sure one could specify these settings in the slurm.conf, but I'd rather not do it unless we're sure of why we want to do it).

**Comment by ltalirz** [comment]
> Also in this case, I get an error in the log: error: Node configuration differs from hardware: Procs=1:2(hw) Boards=1:1(hw) SocketsPerBoard=1:1(hw) CoresPerSocket=1:2(hw) ThreadsPerCore=1:1(hw)

I see, I didn't expect that - if they *know* the hardware configuration, why don't they default to it?

> Note that, however, the user could start the virtual machine with a different number of virtual CPUs.

Yes, that is what I was trying to address by removing the hardcoding.

> From the results above, if the number of vCPUs is > the ones in the slurm configuration, there is no problem.

Well... let's say it still works - but it might not use the full available hardware.

>  One should probably try to reboot the VM with 1 CPU only and see if the queue is completely blocked, or if slurm still works, but overbooks the single vCPU

Yes, we'll need to test that.

>  the problem is simply in the splitting of SocketsPerBoard and CoresPerSocket

If we decide to stay with setting CPU=2, then it probably makes sense to set CoresPerSocket to 2 as well - I think Quantum Mobile is more likely to run on 2 cores on the same socket than on different sockets (e.g. in laptops that basically does not exist).

It seems, slurm internally uses [hwloc](https://www.open-mpi.org/projects/hwloc/) to read the info about the cpu hardware. hwloc is actually available as an apt package:

```
max@qmobile:~$ sudo apt-get install hwloc
...
max@qmobile:~$ hwloc-ls --only CORE --of console 
Core L#0
Core L#1
max@qmobile:~$ hwloc-ls --only SOCKET --of console 
Package L#0
```
We could have a simple bash script start at system startup that modifies the slurm configuration according to `hwloc` output.
Still, I find it a bit silly we need to do this if `slurm` already *knows* about it.


P.S. Just for curiosity (not relevant here): I discovered that you can get this type of info from ansible as well:

```yaml
- debug:
    msg: "procs {{ ansible_processor_count }}"

- debug:
    msg: "vcpus {{ ansible_processor_vcpus }}"

- debug:
    msg: "threads per core {{ ansible_processor_threads_per_core }}"
```

```
TASK [marvel-nccr.slurm : debug] ***********************************************************************************
ok: [default] =>
  msg: procs 1

TASK [marvel-nccr.slurm : debug] ***********************************************************************************
ok: [default] =>
  msg: vcpus 2

TASK [marvel-nccr.slurm : debug] ***********************************************************************************
ok: [default] =>
  msg: threads per core 1
```

**Comment by ltalirz** [comment]
E.g. the following script would do the job:
```bash
cores=`hwloc-ls --only CORE --of console | wc -l`
sockets=`hwloc-ls --only SOCKET --of console | wc -l`
corespersocket=$(( cores / sockets))

echo "NodeName={{ slurm_hostname }} CPUs=$cores Sockets=$sockets CoresPerSocket=$corespersocket State=UNKNOWN"
```
On the workhorse, it does:
```
ubuntu@workhorse:~$ bash hwloc.sh
NodeName={{ slurm_hostname }} CPUs=2 Sockets=1 CoresPerSocket=2 State=UNKNOWN
```

We just need to figure out where to hook in so that it starts at system startup before slurm

**Comment by chrisjsewell** [comment]
BTW I was actually playing around with this recently in https://github.com/chrisjsewell/chris-sewell-epfl/blob/master/qe-performance/ansible-playbook. This was what I implemented, which may or mayn not be of use:

playbook:
```yaml
  vars:
    slurm_hostname: "{{ ansible_hostname }}"
    slurm_cpu_per_socket: "{{ ansible_processor_cores }}"
    slurm_threads_per_core: "{{ ansible_processor_threads_per_core }}"
    slurm_sockets: "{{ ansible_processor_count }}"
    slurm_max_cpus: "{{ ansible_processor_vcpus }}"
```

template:
```jinja2
EnforcePartLimits=ALL
...
NodeName={{ slurm_hostname }} Sockets={{ slurm_sockets }} CoresPerSocket={{ slurm_cpu_per_socket }} ThreadsPerCore={{ slurm_threads_per_core }} State=UNKNOWN
PartitionName=main Nodes={{ slurm_hostname }} Default=YES MaxTime=INFINITE State=UP MaxNodes=1 MaxCPUsPerNode={{ slurm_max_cpus }}
```

> the job remains in the queue forever as resources are missing

Note that `EnforcePartLimits=ALL` above ensures that jobs are cancelled if they exceed the CPU limit, rather than just infinitely queuing them.

**Comment by ltalirz** [comment]
Thanks, yes we noticed in the comments above that one can get this from ansible, which is an improvement, but it does not solve the issue when starting a new VM with a pre-built image.

**Comment by chrisjsewell** [comment]
> but it does not solve the issue when starting a new VM with a pre-built image.

Ah I see, so the VM has to adapt to the "outside world", makes sense.
I think it's still good to have the `EnforcePartLimits=ALL` set though, so jobs fail correctly when asking for too many resources
